### PR TITLE
 Team Compaction

### PR DESCRIPTION
**Pull request by seo-0**
Signed-off-by: seo-0 <lilianapsy@naver.com>
[[analysis]Compaction_week5.pdf](https://github.com/DKU-StarLab/leveldb-study/files/9235967/analysis.Compaction_week5.pdf)

### CODE REVIEW

**Comment by min-guk** [comment]
Please change the file name as I mentioned before and upload it at analysis directory.

**Comment by seo-0** [comment]
[Compaction_week5.pdf](https://github.com/DKU-StarLab/leveldb-study/files/9238883/Compaction_week5.pdf)

**Review by seo-0 — COMMENTED** [review]
[Compaction_week5.pdf](https://github.com/DKU-StarLab/leveldb-study/files/9238887/Compaction_week5.pdf)

**Comment by min-guk** [comment]
Please change the file name as I mentioned before and upload it at analysis directory.

**Pull request merged**
